# Generated by Django 4.1.7 on 2023-02-17 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.CharField(max_length=1000)),
                ('order_time', models.DateTimeField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('discount_rate', models.DecimalField(decimal_places=2, max_digits=20)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('active', models.BooleanField()),
                ('order_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.orderstatus')),
                ('product_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productorder')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
            ],
            options={
                'db_table': 'user_orders',
            },
        ),
    ]
